### ISSUE TITLE
Cannot find module 'semantic-release-replace-plugin'

### ISSUE THREAD

**Issue by TheSlimvReal** [jpoehnelt/semantic-release-replace-plugin#223]
Since version 1.2.1 and later I get the following error in my GitHub workflow that runs semantic release:

```
[5:08:25 AM] [semantic-release] › ℹ  Running semantic-release version 19.0.5
[5:08:25 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Cannot find module 'semantic-release-replace-plugin'
Require stack:
- /home/runner/work/ndb-core/ndb-core/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at resolveFileName (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/resolve-from/index.js:46:47)
    at loadPlugin (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/semantic-release/lib/plugins/utils.js:51:82)
    at /home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/semantic-release/lib/plugins/index.js:17:37
    at Array.reduce (<anonymous>)
    at module.exports (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/semantic-release/lib/plugins/index.js:[14](https://github.com/Aam-Digital/ndb-core/actions/runs/5482968601/jobs/9988838364#step:4:15):34)
    at module.exports (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/semantic-release/lib/get-config.js:84:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/ndb-core/ndb-core/noop.js' ]
}
```

I had to downgrade to `@google/semantic-release-replace-plugin@1.2.0`to make it work again.
Maybe this error has something to do with Node 14 which I have to use in order to fix [this issue](https://github.com/cycjimmy/semantic-release-action/issues/159)

My (failing) workflow:
```
  run-semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      # Only required temporary: https://github.com/cycjimmy/semantic-release-action/issues/159
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ***
          SLACK_WEBHOOK: ***
        with:
          extra_plugins: |
            semantic-release-replace-plugin
            @semantic-release/git
            @semantic-release/github
            semantic-release-slack-bot
```
